name: Unittest Testsuite

on:
  pull_request:
    branches: [main devd]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Download Test Data
        run: |
          dvc pull
      - name: Test with unittest
        run: |
          python -m unittest discover -s tests -p 'test_*.py'
