name: Unittest Testsuite

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  testsuite:
    runs-on: ubuntu-latest
    environment: testsuite
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install GDAL system-wide
        run: |
          sudo apt-get install -y libgdal-dev python3-gdal
      - name: Adjust requirements.txt for GDAL
        run: |
          # GDAL version to be installed by pip must match system-wide version
          sed -i "s/^gdal$/gdal==$(gdal-config --version)/" requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # GDAL needs numpy to be installed first for _gdal_array
          pip install numpy
          pip install -r requirements.txt
      - name: Download Test Data
        run: |
          dvc remote modify --local test_store access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          dvc remote modify --local test_store secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          dvc pull
      - name: Test with unittest
        run: |
          # GDAL fails without LD_PRELOAD of libstdc++.so.6
          LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 python -m unittest discover -s tests -p 'test_*.py'
